# Generated by Django 5.2.7 on 2025-10-16 02:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del proceso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('on_hold', 'En pausa'), ('closed', 'Cerrado')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proceso de selección',
                'verbose_name_plural': 'Procesos de selección',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la etapa')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha objetivo')),
                ('is_blocker', models.BooleanField(default=False, verbose_name='Bloquea avance')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='blog.recruitmentprocess', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['order'],
                'unique_together': {('process', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CandidateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_assignments', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assignments', to='blog.processstage')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='blog.recruitmentprocess', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Asignación de candidato',
                'verbose_name_plural': 'Asignaciones de candidatos',
                'unique_together': {('process', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='StageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Califica utilidad de la etapa (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('visibility', models.CharField(choices=[('team', 'Equipo'), ('candidates', 'Candidatos'), ('private', 'Privado PO')], default='candidates', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='blog.candidateassignment', verbose_name='Asignación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_feedback', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='blog.processstage')),
            ],
            options={
                'verbose_name': 'Feedback de etapa',
                'verbose_name_plural': 'Feedback de etapas',
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'stage')},
            },
        ),
    ]
