# Generated by Django 5.2.8 on 2025-11-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recruitmentprocess_processstage_candidateassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagefeedback',
            name='advice',
            field=models.TextField(blank=True, help_text='¿Qué recomendaciones darías a quienes van a pasar por esta etapa?', verbose_name='Consejos para futuros candidatos'),
        ),
        migrations.AddField(
            model_name='stagefeedback',
            name='cons',
            field=models.TextField(blank=True, help_text='¿Qué podría mejorar en esta etapa?', verbose_name='Áreas de mejora'),
        ),
        migrations.AddField(
            model_name='stagefeedback',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Si activas esto, tu nombre no será visible para otros candidatos', verbose_name='Compartir de forma anónima'),
        ),
        migrations.AddField(
            model_name='stagefeedback',
            name='pros',
            field=models.TextField(blank=True, help_text='¿Qué te pareció útil o valioso de esta etapa?', verbose_name='Aspectos positivos'),
        ),
        migrations.AlterField(
            model_name='stagefeedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comentario general (opcional)'),
        ),
    ]
